version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb


# docker exec -it $(docker ps | grep mongo | cut -d' ' -f1) /bin/bash
# mongo --port 27017 -u root
# root

# use my_db
# db.my_coll.find()

